import {useEffect,useState} from 'react'
import Kitten from '@renderer/components/Kitten'
import VoiceButton from '@renderer/components/VoiceButton'
import ChatInput from '@renderer/components/ChatInput'
import ChatBubbles from '@renderer/components/ChatBubbles'
import {useConversation} from '@renderer/hooks/useConversation'
import {useAcademy} from '@renderer/hooks/useAcademy'
import {courses,defaultProgress,lessonsByLevel,lessonScenesByLevel,type AgeBand,type LearnerProfile,type Lesson} from '@renderer/data/academy'
import {isWebChatMode} from '@renderer/api-web'
import '@renderer/assets/main.css'

type View='home'|'courses'|'lesson'|'tutor'|'progress'|'parent'|'admin'
const nav:[View,string][]=[['home','Today'],['courses','Courses'],['tutor','Tutor'],['progress','Progress'],['parent','Parent view'],['admin','Studio']]

function App():React.JSX.Element{
 const academy=useAcademy(); const [view,setView]=useState<View>('home'); const [onboard,setOnboard]=useState(!academy.profile)
 const [lessonStarted,setLessonStarted]=useState(false); const [selectedLesson,setSelectedLesson]=useState<Lesson|null>(null); const [scene,setScene]=useState(0); const [answer,setAnswer]=useState<string|null>(null); const [limit,setLimit]=useState(()=>{try{return Number(localStorage.getItem('hikid-daily-limit'))||20}catch{return 20}})
 const [startup,setStartup]=useState<'checking'|'ready'|'error'>(isWebChatMode()?'ready':'checking'); const [startupMessage,setStartupMessage]=useState('Preparing your learning studio…')
 const {kittenState,isRecording,isProcessing,messages,servicesReady,error,mode,startRecording,stopRecording,interrupt,setMode,clearMessages}=useConversation()
 useEffect(()=>{if(isWebChatMode()){window.api.startServices().catch(()=>{});return}let alive=true;const fail=(message:string)=>{if(alive){setStartup('error');setStartupMessage(message)}};const unsub=window.api.onServiceStatus(status=>{if(status.ready&&alive)setStartup('ready')});(async()=>{try{setStartupMessage('Checking learning services…');const deps=await window.api.checkDependencies();if(!deps.sox||!deps.espeakNg){fail('A required audio service is missing.');return}setStartupMessage('Checking the local language model…');const models=await window.api.checkModels();if(!models.exists){fail('The local language model is not installed yet.');return}setStartupMessage('Starting Kitten’s studio…');await window.api.startServices()}catch(err){fail(err instanceof Error?err.message:String(err))}})();return()=>{alive=false;unsub()}},[])
 const name=academy.profile?.name||'learner'
 const go=(v:View)=>setView(v)
 const openLesson=(level:string)=>{setSelectedLesson(lessonsByLevel[level]??lessonsByLevel['Pre-A1']);setScene(0);setAnswer(null);setLessonStarted(true);setView('lesson')}
 const profileLevel=academy.profile?.level??'Pre-A1'
 if(startup!=='ready')return <Startup state={startup} message={startupMessage} retry={()=>{setStartup('checking');window.api.startServices().catch(err=>{setStartup('error');setStartupMessage(err instanceof Error?err.message:String(err))})}}/>
 if(onboard)return <Onboarding onSave={(p)=>{academy.saveProfile(p);setOnboard(false)}}/>
 return <div className="app-shell">
  <nav className="nav"><div className="brand"><span className="brand-mark">H</span> HiKid Academy</div><div className="nav-label">Your learning world</div><div className="nav-list">{nav.map(([id,label])=><button aria-current={view===id?'page':undefined} className={view===id?'active':''} onClick={()=>go(id)} key={id} type="button">{label}</button>)}</div><div className="nav-footer">A safe place to find your voice.<br/>Progress is saved on this device.</div></nav>
  <main className="main"><div className="topbar"><div><div className="eyebrow">HiKid Academy / {view}</div><h1>{view==='home'?`Good to see you, ${name}.`:nav.find(n=>n[0]===view)?.[1]}</h1></div><div className="profile-chip"><span className="avatar">{name.slice(0,1).toUpperCase()}</span><span>{academy.profile?.level||'Pre-A1'}</span></div></div>
   {view==='home'&&<Home name={name} progress={academy.progress} onLesson={()=>openLesson(profileLevel)}/>}
   {view==='courses'&&<Courses onLesson={openLesson}/>}
   {view==='lesson'&&selectedLesson&&<Lesson lesson={selectedLesson} started={lessonStarted} scene={scene} setScene={setScene} answer={answer} setAnswer={setAnswer} complete={()=>academy.completeLesson(selectedLesson.id,selectedLesson.duration)} onTutor={()=>setView('tutor')} completed={academy.progress.completedLessonIds.includes(selectedLesson.id)}/>}
   {view==='tutor'&&<Tutor kittenState={kittenState} isRecording={isRecording} isProcessing={isProcessing} servicesReady={servicesReady} error={error} messages={messages} mode={mode} start={startRecording} stop={stopRecording} interrupt={interrupt} setMode={setMode} clear={clearMessages}/>}
   {view==='progress'&&<Progress progress={academy.progress}/>}
   {view==='parent'&&<Parent limit={limit} setLimit={(x)=>{setLimit(x);try{localStorage.setItem('hikid-daily-limit',String(x))}catch{}}} reset={()=>{academy.reset();setOnboard(true)}}/>}
   {view==='admin'&&<Admin/>}
  </main>
 </div>
}
function Startup({state,message,retry}:{state:'checking'|'error';message:string;retry:()=>void}):React.JSX.Element{return <main className="main"><div className="onboarding"><div className="brand"><span className="brand-mark">H</span> HiKid Academy</div><h1>{state==='checking'?'Warming up your studio.':'Let’s get the studio ready.'}</h1><p className="muted">{message}</p>{state==='checking'?<div className="progress"><i style={{width:'58%'}}/></div>:<button className="btn btn-primary" onClick={retry} type="button">Try again</button>}</div></main>}
 function Onboarding({onSave}:{onSave:(p:LearnerProfile)=>void}):React.JSX.Element{const [name,setName]=useState('');const [age,setAge]=useState<AgeBand>('9–12');const [level,setLevel]=useState('Pre-A1');const [minutes,setMinutes]=useState(15);return <main className="main"><div className="onboarding"><div className="eyebrow">A new chapter starts here</div><h1>Find your<br/><span style={{color:'var(--cat)'}}>bright voice.</span></h1><p className="muted">A private learning space built for curious minds. Tell us a little about the learner.</p><div className="form-grid"><div className="field"><label htmlFor="name">Learner name</label><input id="name" value={name} onChange={e=>setName(e.target.value)} placeholder="What should we call you?" /></div><div className="field"><label>Age band</label><div className="choice-row">{(['5–8','9–12','13–15'] as AgeBand[]).map(x=><button aria-pressed={age===x} type="button" className={`choice ${age===x?'selected':''}`} onClick={()=>setAge(x)} key={x}>{x}</button>)}</div></div><div className="field"><label htmlFor="level">Current English level</label><select id="level" value={level} onChange={e=>setLevel(e.target.value)}>{courses.map(c=><option key={c.level}>{c.level}</option>)}</select></div><div className="field"><label>Daily goal</label><div className="choice-row">{[10,15,20,30].map(x=><button aria-pressed={minutes===x} type="button" className={`choice ${minutes===x?'selected':''}`} onClick={()=>setMinutes(x)} key={x}>{x} min</button>)}</div></div><button className="btn btn-primary" disabled={!name.trim()} onClick={()=>onSave({name:name.trim(),ageBand:age,level,dailyGoalMinutes:minutes})} type="button">Enter my academy</button></div></div></main>}
 function Home({name,progress,onLesson}:{name:string;progress:typeof defaultProgress;onLesson:()=>void}):React.JSX.Element{return <div className="grid"><section className="hero"><div className="eyebrow" style={{color:'var(--yellow)'}}>Today’s small win for {name}</div><h2>Your voice gets<br/>brighter every day.</h2><p>One short lesson. One brave try. Let’s make today count.</p><button className="btn btn-primary" onClick={onLesson} type="button">Continue lesson <span>→</span></button></section><div className="stat-row"><div className="card stat"><div><small>Current streak</small><strong>{progress.streak} days</strong></div><span className="pill">On a roll</span></div><div className="card stat"><div><small>Learning time</small><strong>{progress.minutes} min</strong></div><span className="pill">This week</span></div><div className="card stat"><div><small>Next milestone</small><strong>2 lessons</strong></div><span className="pill">Almost there</span></div></div><div className="section-head"><h2>Today’s learning plan</h2><span className="muted">12 minutes</span></div><div className="card lesson-card"><div className="lesson-icon">01</div><div><span className="eyebrow">Speak & listen</span><h3>A brave hello</h3><p className="muted">Introduce yourself and ask one friendly question.</p></div><button className="btn btn-quiet" onClick={onLesson} type="button">Start</button></div></div>}
 function Courses({onLesson}:{onLesson:(level:string)=>void}):React.JSX.Element{return <div><p className="muted">A six-level path from first words to fluent expression. Pick a world to explore.</p><div className="course-grid">{courses.map(c=><article className="card course-card" key={c.level}><div className="course-color" style={{background:c.color}}/><div className="course-body"><span className="pill">{c.level}</span><h3>{c.title}</h3><p className="muted">{c.description}</p>{c.units.map(u=><div className="unit" key={u.id}><span>{u.title}</span><span className="muted">{u.lessons} lessons</span></div>)}<button className="btn btn-quiet" onClick={()=>onLesson(c.level)} type="button">Preview a lesson</button></div></article>)}</div></div>}
 function Lesson({lesson,started,scene,setScene,answer,setAnswer,complete,onTutor,completed}:{lesson:Lesson;started:boolean;scene:number;setScene:(x:number)=>void;answer:string|null;setAnswer:(x:string)=>void;complete:()=>boolean|void;onTutor:()=>void;completed:boolean}):React.JSX.Element{const frames=lessonScenesByLevel[Object.keys(lessonsByLevel).find(k=>lessonsByLevel[k].id===lesson.id)??'Pre-A1'];const [feedback,setFeedback]=useState(completed?'Lesson already complete. Progress is safe.':'');return <div className="lesson-layout"><div className="section-head"><div><div className="eyebrow">Structured lesson · {lesson.type}</div><h2>{lesson.title}</h2><p className="muted">{lesson.objective}</p></div><span className="pill">{lesson.duration} min</span></div><section className="video"><div className="video-scene"><span className="eyebrow" style={{color:frames[scene].accent}}>Pip’s story · scene {scene+1}</span><h2>{frames[scene].heading}</h2><p>{frames[scene].body}</p><strong>{frames[scene].spokenText}</strong></div><div className="scene-controls"><button className="btn btn-primary" aria-label="Play lesson scene" onClick={()=>setScene((scene+1)%frames.length)} type="button">{started?'Replay scene':'Play scene'}</button><button className="btn btn-light" onClick={()=>setScene(Math.max(0,scene-1))} type="button">Back</button><div className="scene-dots">{frames.map((_,i)=><i className={i===scene?'on':''} key={i}/>)}</div></div></section><div className="lesson-columns"><section className="card"><div className="eyebrow">Words to keep</div><h3>Say it like you mean it.</h3><div className="vocab">{lesson.vocabulary.map(w=><span className="word" key={w}>{w}</span>)}</div><button className="btn btn-quiet" style={{marginTop:20}} onClick={onTutor} type="button">Practice with Pip</button></section><section className="card"><div className="eyebrow">Quick check</div><h3>Which word belongs in this lesson?</h3><div className="quiz-options">{[lesson.vocabulary[0],lesson.vocabulary[1], 'perhaps'].map((x,i)=><button aria-pressed={answer===x} className={answer?(i===0?'correct':'wrong'):''} onClick={()=>setAnswer(x)} type="button" key={x}>{x}</button>)}</div>{answer&&<p className="muted">{answer===lesson.vocabulary[0]?'Correct. You spotted the lesson word.':'Good try. Listen once more and choose the first word.'}</p>}</section></div><button className="btn btn-primary" style={{marginTop:18}} disabled={completed} onClick={()=>{if(!completed){complete();setFeedback('Lesson complete. Your progress has been updated.')}}} type="button">{completed?'Completed':'Complete lesson'}</button>{feedback&&<p className="muted" role="status">{feedback}</p>}</div>}
 function Tutor(p:{kittenState:any;isRecording:boolean;isProcessing:boolean;servicesReady:boolean;error:string|null;messages:any[];mode:'press-and-hold'|'vad';start:()=>void;stop:()=>void;interrupt:()=>void;setMode:(x:'press-and-hold'|'vad')=>void;clear:()=>void}):React.JSX.Element{return <div className="grid"><section className="hero"><div className="eyebrow" style={{color:'var(--yellow)'}}>Private speaking studio</div><h2>Talk it out.<br/>I’m listening.</h2><p>Practice at your pace. Pip will keep the conversation friendly and focused.</p><div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button aria-pressed={p.mode==='press-and-hold'} className="btn btn-primary" onClick={()=>p.setMode('press-and-hold')} type="button">Hold to speak</button><button aria-pressed={p.mode==='vad'} className="btn btn-light" onClick={()=>p.setMode('vad')} type="button">Auto listen</button></div></section><div className="card" style={{display:'grid',placeItems:'center',gap:12}}><Kitten state={p.kittenState}/>{p.mode==='press-and-hold'?<VoiceButton isRecording={p.isRecording} onPointerDown={p.start} onPointerUp={p.stop} disabled={!p.servicesReady||p.isProcessing}/>:<div className="vad-indicator"><span className="vad-dot"/><strong>{p.isProcessing?'Thinking…':'Auto listening'}</strong></div>}<span className="muted">{p.isProcessing?'Thinking…':p.isRecording?'Listening…':p.kittenState==='speaking'?'Pip is speaking':'Ready when you are'}</span>{(p.isProcessing||p.kittenState==='speaking')&&<button className="btn btn-quiet" onClick={p.interrupt} type="button">Stop</button>}</div>{p.error&&<div className="card" style={{color:'var(--coral)'}}>The studio needs a moment. {p.error}</div>}<div className="card" style={{minHeight:160}}><div className="section-head" style={{margin:0}}><h3>Conversation</h3><button className="btn btn-quiet" onClick={p.clear} type="button">Clear</button></div><ChatBubbles messages={p.messages} visible aiName="Pip"/><ChatInput disabled={!p.servicesReady||p.isProcessing} onSend={t=>{window.api.sendMessage(t).catch(()=>{})}} placeholder="Type to Pip…"/></div></div>}
function Progress({progress}:{progress:typeof defaultProgress}):React.JSX.Element{return <div><div className="hero"><div className="eyebrow" style={{color:'var(--yellow)'}}>Your learning signal</div><h2>Small practice.<br/>Real progress.</h2><p>You have built {progress.minutes} minutes of learning time. Keep the rhythm gentle and steady.</p></div><div className="section-head"><h2>Skill constellation</h2><span className="muted">Updated just now</span></div><div className="card skill-list">{Object.entries(progress.skillScores).map(([k,v])=><div className="skill-line" key={k}><header><span>{k}</span><span>{v}%</span></header><div className="progress"><i style={{width:`${v}%`}}/></div></div>)}</div></div>}
 function Parent({limit,setLimit,reset}:{limit:number;setLimit:(x:number)=>void;reset:()=>void}):React.JSX.Element{return <div className="grid"><div className="hero"><div className="eyebrow" style={{color:'var(--yellow)'}}>A calm view for grown-ups</div><h2>See the pattern,<br/>not just the score.</h2><p>This week: 42 minutes across 4 learning days. Speaking is becoming a clear strength.</p></div><div className="lesson-columns"><section className="card"><div className="eyebrow">Weekly summary</div><h3>Strengths</h3><p>Listening confidence and vocabulary recall are moving together.</p><h3>Good next step</h3><p>Invite one short speaking practice after dinner.</p><button className="btn btn-quiet" onClick={reset} type="button">Reset learner profile</button></section><section className="card"><div className="eyebrow">Daily limits</div><h3>Learning time</h3><p className="muted">Prototype setting: saved on this device for planning; it is not enforced yet.</p><input aria-label="Daily limit" type="range" min="10" max="60" value={limit} onChange={e=>setLimit(Number(e.target.value))} style={{width:'100%'}}/><strong>{limit} minutes per day</strong><hr/><label><input type="checkbox" defaultChecked/> Prototype privacy preference (local only)</label></section></div></div>}
function Admin():React.JSX.Element{const [filter,setFilter]=useState('All');const rows=[['A brave hello','Pre-A1','Published'],['Meet the weather','A1','Published'],['The big idea','A2','In review'],['City signals','B1','Draft'],['Elegant arguments','C1','Draft']];return <div><div className="tabs">{['All','Published','In review','Draft'].map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} type="button" key={x}>{x}</button>)}</div><div className="card"><table className="admin-table"><thead><tr><th>Content</th><th>Level</th><th>Status</th></tr></thead><tbody>{rows.filter(r=>filter==='All'||r[2]===filter).map(r=><tr key={r[0]}><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td><span className="pill">{r[2]}</span></td></tr>)}</tbody></table></div></div>}
export default App